### ISSUE TITLE
Замечания, защита

### ISSUE THREAD

**Issue by ananasn** [Bagautdino/Lab-4#1]
* Класс `Main` совсем бесполезный, с одним статическим методом. В какой момент вам понадобиться делать много разных экземпляров? Я думаю, что либо достаточно было сделать функцию `main()` и в ней показать работу остальных классов. Либо переделать класс `Main` в класс `Game`. И добавить туда какие-нибудь соответствующие атрибуты. Например, атрибуты экземпляра класса `Game` такие как: `self.mode`, `self.max_points` что-то еще. Добавить в класс `Game` методы `run_dialog()`, `start_game()`, `check_winner()`, `add_player()`.

 Класс обычно представляет какую-то конкретную сущность, вещь из предметной области.  Класс нужен для того, чтобы упорядочить описание объекта (его поведение, описываемое методами и свойства, выражающиеся атрибутами).  Класс `Main` этого не делает у вас. Я бы сделала класс Game следующим образом:
```python3
class Game:

    def __init__(self, mode='0', players=[]):
        self.mode = mode
        self.players = players
        self.cube = Cube() #  fill_suits() fill_values() можно вызывать в init Cube

    def chose_mode(self):
        print('\n\t1) Игрок Vs. Компьютера'
              '\n\t2) Мультиплеер'
              '\n\t0) Выход')
        print('\n\nВыберите режим: ')
        self.mode = input()

    def start_game(self):
        if self.mode == '0':
            self.stop_game()
            return
        elif self.mode == '1':
            self.single_game()
        elif self.mode == '2':
            number = int(input('К-во игроков: '))
            self.multiplayer_game(number)
        self.check_winner()
        self.clear_game()
        self.chose_mode()

    def single_game(self):
        print("\n\n[  Игрок    V S.   Компьютер  ]")
        self.add_payer(Player())
        self.add_payer(Cpu())
        self.run_game()

    def multiplayer_game(self, number=2):
        print("\n\n[  Мультиплеер  ]")
        for i in range(number):
            self.add_payer(Player())
        self.run_game()

    def run_game(self):
        while self.cube.endgame_points < 8:
            for player in self.players:
                time.sleep(2)
                self.cube.show_cubes()
                print(f'\n\n{player.name} теперь твоя очередь...') # В класе CPU self.name = "Компьютер"
                player.choose_cube()
                self.cube.update_endgame_points()

    def clear_game(self):
        self.cube = Cube()
        self.players.clear()

    def stop_game(self):
        print('Хорошего дня! До свидания.')

    def check_winner(self):
        winner = max(self.players, key=lambda p: p.score)
        print(f'\nПобедитель {winner.name}')
        print('Окончательный счет: ')
        for player in self.players:
            print(f'{player.name}: {player.score}')

    def add_payer(self, player):
        self.players.append(player)


if __name__ == '__main__':
    g = Game()
    g.chose_mode()
    g.start_game()

```

* Для защиты работы посмотрите на предложенный мной класс Game и задайте мне три вопроса по моментам, которые могут быть непонятны (можно больше).

**Comment by Bagautdino** [comment]
1) Зачем писать в конструкторе mode='0'?
2) Зачем в функцию multuplayer_game передавать number=2, если у нас пользователь вводит количество игроков до этого?
3) self.add_payer(Player())
        self.add_payer(Cpu()). Вы таким образом наследуетесь от класса?
4) Правильно ли была сделана UML? Если нет то я переделаю.

**Comment by ananasn** [comment]
На всякий случай отвечу на вопросы, если вы еще не выяснили ответы.

1.  Это (`mode='0'`) параметр по умолчанию. Т.е. если его передавать при создании экземпляра `game = Game('1')`, то значение `'0'` будет игнорироваться. 
```python
game = Game('1')  # или вот так можно передавать `Game(mode='1')`
print(game.mode) # напечатает '1'
```
Но если ничего не передавать этому параметру, то по умолчанию значение будет `'0'`.
```python
game = Game() 
print(game.mode) # напечатает '0'
```
2. Для универсальности. Возможно кто-то будет использовать этот класс для создания своей похожей игры, и количество игроков указывать окажется необязательным.

3. Нет. Наследование указывается при опредлелении класса после названия класса. Например,
```python
class  TicTacToeGame(Game):   # Класс TicTacToeGame наследуется от Game
    pass
```
В нашем же случае `self.add_payer(Player())`. Player() -- экземпляр класса, т.е. конкретный новый игрок. Делая Player()  мы фактически создаем экземпляр (нового игрока) и инициализируем его, неявно вызывая конструктор __init__().

4. Правильно
